# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ic5fca_1VP8mRrlZGGQP-RaBooE_WV1b
"""

# =========================================================
# BASELINE: Plain BERT Fine-tuning (NO weighting / NO balancing
#           NO calibration / NO uncertainty / NO selective pred)
# Train -> Validate -> Test
# Progress printing: tqdm + ETA + prints every N steps ✅
# Optimized for GPU (T4) with AMP + pin_memory ✅
# =========================================================

!pip -q install transformers accelerate tqdm

import os, re, random, time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, precision_recall_fscore_support
)

import matplotlib.pyplot as plt
from tqdm.auto import tqdm

from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup
from torch.optim import AdamW


# -----------------------------
# 0) Reproducibility
# -----------------------------
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)


# -----------------------------
# 1) Settings
# -----------------------------
DATA_PATH   = "text.csv"           # your file
MODEL_NAME  = "bert-base-uncased"
NUM_CLASSES = 6
EMOTION_LABELS = ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

TEST_SIZE = 0.20                   # 20% test
VAL_SIZE  = 0.20                   # 20% of remaining 80% -> 16% overall
BATCH_SIZE = 32
MAX_LEN   = 128
LR        = 2e-5
EPOCHS    = 3

OUTPUT_DIR = "./baseline_checkpoints"
os.makedirs(OUTPUT_DIR, exist_ok=True)

LOG_EVERY = 50                     # print every 50 batches

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


# -----------------------------
# 2) Load data
# -----------------------------
df = pd.read_csv(DATA_PATH, index_col=0)
print("Columns:", df.columns.tolist())

# Accept either (text,label) or (Text,Label)
if "text" in df.columns and "label" in df.columns:
    df = df.rename(columns={"text": "Text", "label": "Label"})
elif "Text" in df.columns and "Label" in df.columns:
    pass
else:
    raise ValueError(f"CSV columns found: {df.columns}. Need (text,label) or (Text,Label).")

df = df.dropna()
df["Label"] = df["Label"].astype(int)

print("\n" + "="*70)
print("DATASET STATISTICS")
print("="*70)
print(f"Total samples: {len(df):,}")
print("\nOriginal label distribution:")
label_counts = df["Label"].value_counts().sort_index()
for idx, count in label_counts.items():
    emotion = EMOTION_LABELS[idx] if idx < len(EMOTION_LABELS) else f"Class_{idx}"
    print(f"  Class {idx} ({emotion:<10}): {count:>6,} ({count/len(df)*100:>5.2f}%)")

# Identify minority classes
minority_threshold = label_counts.median()
minority_classes = label_counts[label_counts < minority_threshold].index.tolist()
print(f"\nMinority classes (below median): {minority_classes}")
print("="*70)


# -----------------------------
# 3) Basic text cleaning
# -----------------------------
def clean_text(s: str) -> str:
    s = str(s)
    s = re.sub(r"http\S+", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

df["Text"] = df["Text"].apply(clean_text)
df = df[df["Text"].str.len() > 0].reset_index(drop=True)
print(f"\nAfter cleaning: {len(df):,} samples\n")


# -----------------------------
# 4) Train / Val / Test split (STRATIFIED)
# -----------------------------
X = df["Text"].tolist()
y = df["Label"].values

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=42, stratify=y
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=VAL_SIZE, random_state=42, stratify=y_temp
)

print("="*70)
print("DATA SPLITS")
print("="*70)
print(f"Train: {len(X_train):>6,} samples ({len(X_train)/len(X)*100:>5.1f}%)")
print(f"Val:   {len(X_val):>6,} samples ({len(X_val)/len(X)*100:>5.1f}%)")
print(f"Test:  {len(X_test):>6,} samples ({len(X_test)/len(X)*100:>5.1f}%)")
print("="*70 + "\n")


# -----------------------------
# 5) Tokenization + DataLoaders
# -----------------------------
print("📦 Tokenizing data...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

train_enc = tokenizer(X_train, truncation=True, padding=True, max_length=MAX_LEN, return_tensors="pt")
val_enc   = tokenizer(X_val,   truncation=True, padding=True, max_length=MAX_LEN, return_tensors="pt")
test_enc  = tokenizer(X_test,  truncation=True, padding=True, max_length=MAX_LEN, return_tensors="pt")

train_ds = TensorDataset(train_enc["input_ids"], train_enc["attention_mask"], torch.tensor(y_train, dtype=torch.long))
val_ds   = TensorDataset(val_enc["input_ids"],   val_enc["attention_mask"],   torch.tensor(y_val, dtype=torch.long))
test_ds  = TensorDataset(test_enc["input_ids"],  test_enc["attention_mask"],  torch.tensor(y_test, dtype=torch.long))

# Faster loaders on GPU:
num_workers = 2 if torch.cuda.is_available() else 0
pin_mem = True if torch.cuda.is_available() else False

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=num_workers, pin_memory=pin_mem)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=num_workers, pin_memory=pin_mem)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=num_workers, pin_memory=pin_mem)

print(f"✅ Tokenization complete")
print(f"   Train tokens: {train_enc['input_ids'].shape}")
print(f"   Val tokens:   {val_enc['input_ids'].shape}")
print(f"   Test tokens:  {test_enc['input_ids'].shape}\n")


# -----------------------------
# 6) Baseline model: BERT + linear head
# -----------------------------
class BertBaseline(nn.Module):
    def __init__(self, base_model_name: str, num_classes: int):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(base_model_name)
        self.dropout = nn.Dropout(0.1)
        self.fc = nn.Linear(768, num_classes)

    def forward(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:, 0, :]
        cls = self.dropout(cls)
        logits = self.fc(cls)
        return logits

print("🤖 Initializing BERT baseline model...")
model = BertBaseline(MODEL_NAME, NUM_CLASSES).to(device)
print(f"✅ Model loaded to {device}\n")


# -----------------------------
# 7) Optimizer / Scheduler / Loss (NO class weights)
# -----------------------------
optimizer = AdamW(model.parameters(), lr=LR)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

criterion = nn.CrossEntropyLoss()  # ✅ NO class weights (baseline)

# AMP for faster training on T4
use_amp = torch.cuda.is_available()
scaler = torch.cuda.amp.GradScaler(enabled=use_amp)


# -----------------------------
# 8) Evaluation helper
# -----------------------------
def evaluate(model, loader):
    model.eval()
    all_preds, all_true = [], []
    total_loss = 0.0

    with torch.no_grad():
        for input_ids, attention_mask, labels in loader:
            input_ids = input_ids.to(device, non_blocking=True)
            attention_mask = attention_mask.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            with torch.cuda.amp.autocast(enabled=use_amp):
                logits = model(input_ids, attention_mask)
                loss = criterion(logits, labels)

            total_loss += loss.item()
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_true.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader)
    acc = accuracy_score(all_true, all_preds)
    macro_f1 = f1_score(all_true, all_preds, average="macro")
    weighted_f1 = f1_score(all_true, all_preds, average="weighted")

    return avg_loss, acc, macro_f1, weighted_f1, np.array(all_true), np.array(all_preds)


# -----------------------------
# 9) Training loop (with progress)
# -----------------------------
train_losses, val_losses = [], []
train_accs, val_accs = [], []
train_macro_f1s, val_macro_f1s = [], []

best_val_macro_f1 = -1.0
best_path = os.path.join(OUTPUT_DIR, "best_baseline.pt")

print("="*70)
print("TRAINING BASELINE BERT")
print("="*70)
print(f"Epochs: {EPOCHS}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Learning rate: {LR}")
print(f"Total training steps: {total_steps}")
print(f"AMP enabled: {use_amp}")
print("="*70 + "\n")

for epoch in range(1, EPOCHS + 1):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    all_train_preds, all_train_true = [], []

    start_epoch = time.time()
    pbar = tqdm(train_loader, desc=f"Epoch {epoch}/{EPOCHS}", leave=True)

    for step, (input_ids, attention_mask, labels) in enumerate(pbar, start=1):
        input_ids = input_ids.to(device, non_blocking=True)
        attention_mask = attention_mask.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=use_amp):
            logits = model(input_ids, attention_mask)
            loss = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        running_loss += loss.item()

        preds = torch.argmax(logits, dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        all_train_preds.extend(preds.detach().cpu().numpy())
        all_train_true.extend(labels.detach().cpu().numpy())

        # Live progress bar stats
        pbar.set_postfix(
            loss=f"{loss.item():.4f}",
            acc=f"{(correct/total):.4f}",
            lr=f"{scheduler.get_last_lr()[0]:.2e}"
        )

        # Print every LOG_EVERY steps (plus first step)
        if step % LOG_EVERY == 0 or step == 1:
            elapsed = time.time() - start_epoch
            steps_left = len(train_loader) - step
            eta = (elapsed / step) * steps_left
            print(
                f"Epoch {epoch} | Step {step}/{len(train_loader)} "
                f"| loss={loss.item():.4f} | acc={(correct/total):.4f} "
                f"| elapsed={elapsed/60:.1f}m | ETA~{eta/60:.1f}m"
            )

    train_loss = running_loss / len(train_loader)
    train_acc  = correct / total
    train_macro_f1 = f1_score(all_train_true, all_train_preds, average="macro")

    # Validation
    val_loss, val_acc, val_macro_f1, val_weighted_f1, y_val_true, y_val_pred = evaluate(model, val_loader)

    # Store metrics
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)
    train_macro_f1s.append(train_macro_f1)
    val_macro_f1s.append(val_macro_f1)

    print(f"\n{'='*70}")
    print(f"EPOCH {epoch}/{EPOCHS} SUMMARY")
    print(f"{'='*70}")
    print(f"Train - Loss: {train_loss:.4f} | Acc: {train_acc:.4f} | Macro-F1: {train_macro_f1:.4f}")
    print(f"Val   - Loss: {val_loss:.4f} | Acc: {val_acc:.4f} | Macro-F1: {val_macro_f1:.4f}")
    print(f"{'='*70}\n")

    # Save best model
    if val_macro_f1 > best_val_macro_f1:
        best_val_macro_f1 = val_macro_f1
        torch.save({"model_state_dict": model.state_dict()}, best_path)
        print(f"✅ Saved best checkpoint (Val Macro-F1: {best_val_macro_f1:.4f})\n")

print("="*70)
print("TRAINING COMPLETE")
print("="*70)
print(f"Best validation Macro-F1: {best_val_macro_f1:.4f}")
print("="*70 + "\n")


# -----------------------------
# 10) Load best model & evaluate
# -----------------------------
print("📂 Loading best checkpoint...")
ckpt = torch.load(best_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.to(device)
print("✅ Best model loaded\n")

val_loss, val_acc, val_macro_f1, val_weighted_f1, y_val_true, y_val_pred = evaluate(model, val_loader)
test_loss, test_acc, test_macro_f1, test_weighted_f1, y_test_true, y_test_pred = evaluate(model, test_loader)


# -----------------------------
# 11) Extract logits (for Stage 2 later)
# -----------------------------
print("💾 Extracting logits for calibration...")

def get_logits(model, loader):
    model.eval()
    all_logits, all_labels = [], []
    with torch.no_grad():
        for input_ids, attention_mask, labels in loader:
            input_ids = input_ids.to(device, non_blocking=True)
            attention_mask = attention_mask.to(device, non_blocking=True)
            with torch.cuda.amp.autocast(enabled=use_amp):
                logits = model(input_ids, attention_mask)
            all_logits.append(logits.cpu())
            all_labels.append(labels)
    return torch.cat(all_logits), torch.cat(all_labels)

val_logits, val_labels = get_logits(model, val_loader)
test_logits, test_labels = get_logits(model, test_loader)

logits_path = os.path.join(OUTPUT_DIR, 'baseline_logits.pt')
torch.save({
    'val_logits': val_logits,
    'val_labels': val_labels,
    'test_logits': test_logits,
    'test_labels': test_labels
}, logits_path)
print(f"✅ Logits saved to: {logits_path}\n")


# -----------------------------
# 12) Confidence statistics
# -----------------------------
def get_confidences(model, loader):
    model.eval()
    all_probs, all_labels = [], []
    with torch.no_grad():
        for input_ids, attention_mask, labels in loader:
            input_ids = input_ids.to(device, non_blocking=True)
            attention_mask = attention_mask.to(device, non_blocking=True)
            with torch.cuda.amp.autocast(enabled=use_amp):
                logits = model(input_ids, attention_mask)
            probs = torch.softmax(logits, dim=-1)
            all_probs.append(probs.cpu())
            all_labels.append(labels)

    all_probs = torch.cat(all_probs)
    all_labels = torch.cat(all_labels)

    max_probs, predictions = all_probs.max(dim=1)
    correct = (predictions == all_labels).float()
    return max_probs.numpy(), correct.numpy(), predictions.numpy()

test_confidences, test_correct, test_predictions = get_confidences(model, test_loader)


# -----------------------------
# 13) Print results
# -----------------------------
print("\n" + "="*70)
print("BASELINE RESULTS (Best Checkpoint)")
print("="*70)
print(f"VALIDATION SET:")
print(f"  Loss:        {val_loss:.4f}")
print(f"  Accuracy:    {val_acc:.4f}")
print(f"  Macro-F1:    {val_macro_f1:.4f}")
print(f"  Weighted-F1: {val_weighted_f1:.4f}")
print(f"\nTEST SET:")
print(f"  Loss:        {test_loss:.4f}")
print(f"  Accuracy:    {test_acc:.4f}")
print(f"  Macro-F1:    {test_macro_f1:.4f}")
print(f"  Weighted-F1: {test_weighted_f1:.4f}")
print("="*70 + "\n")


# -----------------------------
# 14) Per-class metrics
# -----------------------------
precision, recall, f1, support = precision_recall_fscore_support(
    y_test_true, y_test_pred, average=None
)

print("="*70)
print("PER-CLASS PERFORMANCE (Test Set)")
print("="*70)
print(f"{'Class':<10} {'Emotion':<12} {'Precision':<12} {'Recall':<12} {'F1-Score':<12} {'Support':<10}")
print("="*70)

for i in range(NUM_CLASSES):
    emotion = EMOTION_LABELS[i] if i < len(EMOTION_LABELS) else f"Class_{i}"
    minority_marker = " ⚠️" if i in minority_classes else ""
    print(f"{i:<10} {emotion:<12} {precision[i]:<12.4f} {recall[i]:<12.4f} {f1[i]:<12.4f} {support[i]:<10}{minority_marker}")

print("="*70)

minority_f1 = f1[minority_classes].mean() if len(minority_classes) > 0 else float("nan")
majority_mask = ~np.isin(range(NUM_CLASSES), minority_classes)
majority_f1 = f1[majority_mask].mean()

print(f"\nMinority classes avg F1: {minority_f1:.4f} ⚠️")
print(f"Majority classes avg F1: {majority_f1:.4f}")
print(f"Gap: {majority_f1 - minority_f1:.4f}")
print("="*70 + "\n")


# -----------------------------
# 15) Confidence analysis
# -----------------------------
print("="*70)
print("CONFIDENCE ANALYSIS (Test Set)")
print("="*70)
print(f"Mean confidence (all):      {test_confidences.mean():.4f}")
print(f"Median confidence:          {np.median(test_confidences):.4f}")
print(f"Mean confidence (correct):  {test_confidences[test_correct==1].mean():.4f}")
print(f"Mean confidence (errors):   {test_confidences[test_correct==0].mean():.4f} ⚠️ OVERCONFIDENT")
print(f"\nConfidence gap: {test_confidences[test_correct==1].mean() - test_confidences[test_correct==0].mean():.4f}")
print("="*70 + "\n")

print("CONFIDENCE BY CLASS:")
print("-"*70)
for i in range(NUM_CLASSES):
    mask = (test_labels.numpy() == i)
    class_conf = test_confidences[mask].mean()
    class_acc = test_correct[mask].mean()
    emotion = EMOTION_LABELS[i] if i < len(EMOTION_LABELS) else f"Class_{i}"
    print(f"Class {i} ({emotion:<10}): Confidence={class_conf:.4f}, Accuracy={class_acc:.4f}")
print("="*70 + "\n")


# -----------------------------
# 16) Classification report
# -----------------------------
print("DETAILED CLASSIFICATION REPORT (Test Set):")
print("="*70)
target_names = [EMOTION_LABELS[i] if i < len(EMOTION_LABELS) else f"Class_{i}" for i in range(NUM_CLASSES)]
print(classification_report(y_test_true, y_test_pred, target_names=target_names, digits=4))
print("="*70 + "\n")


# -----------------------------
# 17) Visualizations (matplotlib only)
# -----------------------------
print("📊 Generating visualizations...\n")

# Confusion Matrix
cm = confusion_matrix(y_test_true, y_test_pred)
plt.figure(figsize=(10, 8))
plt.imshow(cm, interpolation='nearest', cmap='Blues')
plt.title('Confusion Matrix (Test Set) - Baseline BERT', fontsize=14, pad=15)
plt.colorbar(label='Count')
plt.xticks(range(NUM_CLASSES), EMOTION_LABELS, rotation=45, ha='right')
plt.yticks(range(NUM_CLASSES), EMOTION_LABELS)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)

thresh = cm.max() / 2
for i in range(NUM_CLASSES):
    for j in range(NUM_CLASSES):
        plt.text(j, i, format(cm[i, j], 'd'),
                 ha="center", va="center",
                 color="white" if cm[i, j] > thresh else "black")

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'confusion_matrix_baseline.png'), dpi=300, bbox_inches='tight')
plt.show()

# Training curves
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

axes[0, 0].plot(range(1, len(train_losses)+1), train_losses, 'o-', label='Train Loss', linewidth=2)
axes[0, 0].plot(range(1, len(val_losses)+1), val_losses, 's-', label='Val Loss', linewidth=2)
axes[0, 0].set_title('Loss Curves', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].set_ylabel('Loss')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].plot(range(1, len(train_accs)+1), train_accs, 'o-', label='Train Acc', linewidth=2)
axes[0, 1].plot(range(1, len(val_accs)+1), val_accs, 's-', label='Val Acc', linewidth=2)
axes[0, 1].set_title('Accuracy Curves', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].set_ylabel('Accuracy')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

axes[1, 0].plot(range(1, len(train_macro_f1s)+1), train_macro_f1s, 'o-', label='Train Macro-F1', linewidth=2)
axes[1, 0].plot(range(1, len(val_macro_f1s)+1), val_macro_f1s, 's-', label='Val Macro-F1', linewidth=2)
axes[1, 0].set_title('Macro-F1 Curves', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('Epoch')
axes[1, 0].set_ylabel('Macro-F1')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

axes[1, 1].bar(range(NUM_CLASSES), f1)
axes[1, 1].set_title('Per-Class F1 Scores (Test)', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('Class')
axes[1, 1].set_ylabel('F1 Score')
axes[1, 1].set_xticks(range(NUM_CLASSES))
axes[1, 1].set_xticklabels(EMOTION_LABELS, rotation=45, ha='right')
axes[1, 1].axhline(y=test_macro_f1, linestyle='--', label=f'Macro-F1: {test_macro_f1:.3f}')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'training_curves_baseline.png'), dpi=300, bbox_inches='tight')
plt.show()

# Confidence distribution
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.hist(test_confidences[test_correct==1], bins=30, alpha=0.7, label='Correct')
ax1.hist(test_confidences[test_correct==0], bins=30, alpha=0.7, label='Incorrect')
ax1.set_xlabel('Confidence', fontsize=12)
ax1.set_ylabel('Frequency', fontsize=12)
ax1.set_title('Confidence Distribution by Correctness', fontsize=12, fontweight='bold')
ax1.legend()
ax1.grid(True, alpha=0.3, axis='y')

conf_by_class = [test_confidences[test_labels.numpy() == i] for i in range(NUM_CLASSES)]
ax2.boxplot(conf_by_class, labels=EMOTION_LABELS)
ax2.set_xlabel('Emotion Class', fontsize=12)
ax2.set_ylabel('Confidence', fontsize=12)
ax2.set_title('Confidence Distribution by Class', fontsize=12, fontweight='bold')
ax2.set_xticklabels(EMOTION_LABELS, rotation=45, ha='right')
ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'confidence_analysis_baseline.png'), dpi=300, bbox_inches='tight')
plt.show()

print("✅ Visualizations saved\n")


# -----------------------------
# 18) Summary for paper
# -----------------------------
print("\n" + "="*70)
print("SUMMARY FOR PAPER")
print("="*70)
print(f"\nBASELINE BERT (No calibration, no uncertainty, no selective prediction)")
print(f"\nTest Performance:")
print(f"  • Accuracy:    {test_acc:.4f}")
print(f"  • Macro-F1:    {test_macro_f1:.4f}")
print(f"  • Weighted-F1: {test_weighted_f1:.4f}")
print(f"\nClass Imbalance Impact:")
print(f"  • Minority classes F1: {minority_f1:.4f}")
print(f"  • Majority classes F1: {majority_f1:.4f}")
print(f"  • Performance gap:     {majority_f1 - minority_f1:.4f}")
print(f"\nReliability Issues:")
print(f"  • Mean confidence on errors: {test_confidences[test_correct==0].mean():.4f}")
print(f"  • Model is overconfident on incorrect predictions")
print(f"  • No mechanism for selective prediction")
print(f"\n➡️  Next step: Run Stage 2 (Temperature Scaling) using saved logits")
print("="*70 + "\n")


# -----------------------------
# 19) Save results to CSV
# -----------------------------
results_dict = {
    'metric': ['test_accuracy', 'test_macro_f1', 'test_weighted_f1',
               'minority_f1', 'majority_f1', 'f1_gap',
               'mean_confidence_all', 'mean_confidence_correct', 'mean_confidence_errors',
               'confidence_gap'],
    'value': [test_acc, test_macro_f1, test_weighted_f1,
              minority_f1, majority_f1, majority_f1 - minority_f1,
              float(test_confidences.mean()),
              float(test_confidences[test_correct==1].mean()),
              float(test_confidences[test_correct==0].mean()),
              float(test_confidences[test_correct==1].mean() - test_confidences[test_correct==0].mean())]
}

results_df = pd.DataFrame(results_dict)
results_csv_path = os.path.join(OUTPUT_DIR, 'baseline_results.csv')
results_df.to_csv(results_csv_path, index=False)
print(f"📊 Results saved to: {results_csv_path}")

per_class_df = pd.DataFrame({
    'class': range(NUM_CLASSES),
    'emotion': EMOTION_LABELS,
    'precision': precision,
    'recall': recall,
    'f1_score': f1,
    'support': support,
    'is_minority': [i in minority_classes for i in range(NUM_CLASSES)]
})
per_class_csv_path = os.path.join(OUTPUT_DIR, 'baseline_per_class.csv')
per_class_df.to_csv(per_class_csv_path, index=False)
print(f"📊 Per-class results saved to: {per_class_csv_path}")

print("\n" + "="*70)
print("BASELINE TRAINING COMPLETE ✅")
print("="*70)
print("\nSaved files:")
print(f"  • Model checkpoint:  {best_path}")
print(f"  • Logits:            {logits_path}")
print(f"  • Results CSV:       {results_csv_path}")
print(f"  • Per-class CSV:     {per_class_csv_path}")
print(f"  • Confusion matrix:  {os.path.join(OUTPUT_DIR, 'confusion_matrix_baseline.png')}")
print(f"  • Training curves:   {os.path.join(OUTPUT_DIR, 'training_curves_baseline.png')}")
print(f"  • Confidence plots:  {os.path.join(OUTPUT_DIR, 'confidence_analysis_baseline.png')}")
print("\n➡️  Next step: Run Stage 2 (Temperature Scaling) using saved logits")
print("="*70)

# ============================
# Paper-ready Class Distribution Plot (Correct % alignment)
# ============================

import pandas as pd
import matplotlib.pyplot as plt

# --------- USER SETTINGS ----------
DATA_PATH = "text.csv"
LABEL_COL = "label"        # <-- change to your label column name
FIG_PATH  = "class_distribution.png"
TITLE     = "Class Distribution"
# ----------------------------------

# 1) Load
df = pd.read_csv(DATA_PATH)

if LABEL_COL not in df.columns:
    raise ValueError(f"Column '{LABEL_COL}' not found. Available columns: {list(df.columns)}")

# 2) Counts (single source of truth)
# Option A: keep numeric order 0..K (recommended if labels are ints)
try:
    # If labels are numeric-like, sort by class index
    df[LABEL_COL] = pd.to_numeric(df[LABEL_COL])
    class_counts = df[LABEL_COL].value_counts().sort_index()
except Exception:
    # If labels are strings (e.g., 'joy', 'sadness'), sort by frequency (descending)
    class_counts = df[LABEL_COL].value_counts()

total = int(class_counts.sum())
percents = (class_counts / total) * 100

# 3) Sanity check (prints what you will plot)
summary = pd.DataFrame({
    "count": class_counts.astype(int),
    "percent": percents.round(2)
})
print("\nClass distribution summary:")
print(summary)
print(f"\nTotal samples = {total}")
print(f"Percent sum   = {percents.sum():.6f}% (should be ~100%)")

# 4) Plot
plt.figure(figsize=(8, 5))
x = list(class_counts.index)
y = list(class_counts.values)

bars = plt.bar(range(len(x)), y)

plt.title(TITLE, fontsize=15)
plt.xlabel("Class", fontsize=13)
plt.ylabel("Number of Samples", fontsize=13)
plt.xticks(range(len(x)), x, fontsize=11)
plt.yticks(fontsize=11)
plt.grid(axis="y", linestyle="--", alpha=0.35)

# 5) Percentage labels (aligned with the SAME bars)
for i, count in enumerate(y):
    pct = (count / total) * 100
    # place label inside bar if tall enough, else above
    if count > max(y) * 0.12:
        plt.text(i, count * 0.95, f"{pct:.1f}%", ha="center", va="top", fontsize=10, color="white")
    else:
        plt.text(i, count + max(y) * 0.01, f"{pct:.1f}%", ha="center", va="bottom", fontsize=10)

plt.tight_layout()

# 6) Save (paper-ready)
plt.savefig(FIG_PATH, dpi=300, bbox_inches="tight")
plt.show()

print(f"\nSaved figure to: {FIG_PATH}")

# =========================================================
# STAGE 2: Temperature Scaling (Compute + Save + Visualizations)
# Input : ./baseline_checkpoints/baseline_logits.pt
# Output: ./baseline_checkpoints/temperature_scaling_stage2.pt
# Saves : temperature + calibrated logits + labels + ECE before/after
# Also saves: reliability diagrams + confidence histograms as PNG
# =========================================================

import os
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# -----------------------------
# Paths
# -----------------------------
out_dir = "./baseline_checkpoints"
os.makedirs(out_dir, exist_ok=True)

stage1_path = os.path.join(out_dir, "baseline_logits.pt")
stage2_path = os.path.join(out_dir, "temperature_scaling_stage2.pt")

if not os.path.exists(stage1_path):
    raise FileNotFoundError(f"❌ Not found: {stage1_path} (Run Stage 1 first)")

print("Stage 1:", stage1_path)
print("Stage 2 (will save to):", stage2_path)

# -----------------------------
# Load Stage 1 logits
# -----------------------------
data1 = torch.load(stage1_path, map_location="cpu")
val_logits  = data1["val_logits"].float()
val_labels  = data1["val_labels"].long()
test_logits = data1["test_logits"].float()
test_labels = data1["test_labels"].long()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
criterion = nn.CrossEntropyLoss()

# -----------------------------
# ECE (Expected Calibration Error)
# -----------------------------
@torch.no_grad()
def ece_score(probs: torch.Tensor, labels: torch.Tensor, n_bins: int = 15) -> float:
    conf, pred = probs.max(dim=1)
    acc = (pred == labels).float()
    bins = torch.linspace(0, 1, n_bins + 1, device=probs.device)
    ece = torch.zeros(1, device=probs.device)

    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        in_bin = (conf > lo) & (conf <= hi)
        if in_bin.any():
            bin_acc = acc[in_bin].mean()
            bin_conf = conf[in_bin].mean()
            bin_frac = in_bin.float().mean()
            ece += torch.abs(bin_acc - bin_conf) * bin_frac

    return float(ece.item())

# -----------------------------
# Temperature scaling model
# -----------------------------
class TemperatureScaler(nn.Module):
    def __init__(self, init_T=1.0):
        super().__init__()
        self.log_T = nn.Parameter(torch.log(torch.tensor([init_T], dtype=torch.float32)))

    def forward(self, logits):
        T = torch.exp(self.log_T)
        return logits / T

    def temperature(self):
        return float(torch.exp(self.log_T).detach().cpu().item())

# -----------------------------
# Load T if exists, else fit on VAL
# -----------------------------
T = None
if os.path.exists(stage2_path):
    try:
        data2 = torch.load(stage2_path, map_location="cpu")
        if "temperature" in data2:
            T = float(data2["temperature"])
            print(f"✅ Loaded existing temperature T = {T:.4f}")
    except Exception:
        T = None

if T is None:
    print("⚠️ No saved temperature found, fitting T on VAL now...")

    scaler = TemperatureScaler(init_T=1.0).to(device)
    vL = val_logits.to(device)
    vY = val_labels.to(device)

    opt = torch.optim.LBFGS([scaler.log_T], lr=0.1, max_iter=100)

    def closure():
        opt.zero_grad()
        loss = criterion(scaler(vL), vY)
        loss.backward()
        return loss

    opt.step(closure)
    T = scaler.temperature()
    print(f"✅ Learned temperature T = {T:.4f}")

# -----------------------------
# Calibrated logits + probs
# -----------------------------
val_logits_cal  = val_logits / T
test_logits_cal = test_logits / T

test_probs_uncal = torch.softmax(test_logits, dim=1)
test_probs_cal   = torch.softmax(test_logits_cal, dim=1)

ece_before = ece_score(test_probs_uncal, test_labels, n_bins=15)
ece_after  = ece_score(test_probs_cal,   test_labels, n_bins=15)

print(f"\nECE (TEST) before: {ece_before:.4f}")
print(f"ECE (TEST) after : {ece_after:.4f}")

# -----------------------------
# SAVE Stage 2 outputs (IMPORTANT for Stage 3 & 4)
# -----------------------------
torch.save({
    "temperature": T,
    "val_logits_calibrated": val_logits_cal,
    "test_logits_calibrated": test_logits_cal,
    "val_labels": val_labels,
    "test_labels": test_labels,
    "ece_test_before": ece_before,
    "ece_test_after": ece_after
}, stage2_path)

print("✅ Saved Stage 2 file:", stage2_path)

# -----------------------------
# Reliability bins (for plotting)
# -----------------------------
def reliability_bins(probs, labels, n_bins=15):
    conf, pred = probs.max(dim=1)
    correct = (pred == labels).float()

    bins = torch.linspace(0, 1, n_bins + 1)
    centers, accs, confs = [], [], []

    for i in range(n_bins):
        lo, hi = bins[i].item(), bins[i+1].item()
        in_bin = (conf > lo) & (conf <= hi)
        if in_bin.any():
            centers.append((lo + hi) / 2)
            accs.append(correct[in_bin].mean().item())
            confs.append(conf[in_bin].mean().item())

    return np.array(centers), np.array(accs), np.array(confs)

def save_reliability_plot(probs, labels, title, save_path, n_bins=15):
    centers, accs, confs = reliability_bins(probs, labels, n_bins=n_bins)

    plt.figure(figsize=(7, 6))
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.bar(centers, accs, width=1/n_bins, alpha=0.7, edgecolor="black", label="Accuracy per bin")
    plt.scatter(centers, confs, marker="o", label="Mean confidence per bin")
    plt.xlabel("Confidence")
    plt.ylabel("Accuracy")
    plt.title(title)
    plt.ylim(0, 1)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()
    print("✅ Saved:", save_path)

# -----------------------------
# Confidence histogram
# -----------------------------
def save_conf_hist(probs, labels, title, save_path):
    conf, pred = probs.max(dim=1)
    correct = (pred == labels)

    plt.figure(figsize=(8, 5))
    plt.hist(conf[correct].numpy(), bins=30, alpha=0.7, label="Correct", edgecolor="black")
    plt.hist(conf[~correct].numpy(), bins=30, alpha=0.7, label="Incorrect", edgecolor="black")
    plt.xlabel("Confidence (max softmax prob)")
    plt.ylabel("Frequency")
    plt.title(title)
    plt.grid(True, alpha=0.3, axis="y")
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()
    print("✅ Saved:", save_path)

# -----------------------------
# SAVE PLOTS (before/after)
# -----------------------------
save_reliability_plot(
    test_probs_uncal, test_labels,
    title="TEST Reliability (Before Calibration)",
    save_path=os.path.join(out_dir, "stage2_reliability_before.png"),
    n_bins=15
)

save_reliability_plot(
    test_probs_cal, test_labels,
    title="TEST Reliability (After Temperature Scaling)",
    save_path=os.path.join(out_dir, "stage2_reliability_after.png"),
    n_bins=15
)

save_conf_hist(
    test_probs_uncal, test_labels,
    title="TEST Confidence Histogram (Before Calibration)",
    save_path=os.path.join(out_dir, "stage2_confidence_hist_before.png")
)

save_conf_hist(
    test_probs_cal, test_labels,
    title="TEST Confidence Histogram (After Calibration)",
    save_path=os.path.join(out_dir, "stage2_confidence_hist_after.png")
)

print("\n✅ Stage 2 done. Files saved in baseline_checkpoints/.")

import torch

data2 = torch.load("temperature_scaling_stage2.pt", map_location="cpu")
T = float(data2["temperature"])
print("Loaded temperature T =", T)

import torch

# ===============================
# 1) Load logits from Stage 1
# ===============================
data1 = torch.load("baseline_logits.pt", map_location="cpu")

test_logits = data1["test_logits"].float()
test_labels = data1["test_labels"].long()

# ===============================
# 2) Load temperature T (Stage 2)
# ===============================
data2 = torch.load("temperature_scaling_stage2.pt", map_location="cpu")
T = float(data2["temperature"])
print("Loaded temperature T =", T)

# ===============================
# 3) Compute probabilities
# ===============================
test_logits_cal = test_logits / T

test_probs_uncal = torch.softmax(test_logits, dim=1)
test_probs_cal   = torch.softmax(test_logits_cal, dim=1)

# ===============================
# 4) ECE function
# ===============================
def compute_ece(probs, labels, n_bins=15):
    conf, pred = probs.max(dim=1)
    correct = (pred == labels).float()

    bins = torch.linspace(0, 1, n_bins + 1)
    ece = torch.tensor(0.0)
    N = probs.size(0)

    for i in range(n_bins):
        lo, hi = bins[i], bins[i + 1]
        in_bin = (conf > lo) & (conf <= hi)
        if in_bin.any():
            acc_bin  = correct[in_bin].mean()
            conf_bin = conf[in_bin].mean()
            ece += (in_bin.float().sum() / N) * torch.abs(acc_bin - conf_bin)

    return float(ece.item())

# ===============================
# 5) Compute ECE before / after
# ===============================
ece_before = compute_ece(test_probs_uncal, test_labels, n_bins=15)
ece_after  = compute_ece(test_probs_cal,   test_labels, n_bins=15)

print(f"ECE before calibration: {ece_before:.4f}")
print(f"ECE after  calibration: {ece_after:.4f}")

# =========================================================
# STAGE 3 (UPDATED, ONE CELL): Uncertainty Quantification
# Reads:  ./baseline_checkpoints/temperature_scaling_stage2.pt
# Writes: ./baseline_checkpoints/uncertainty_stage3.pt
#         ./baseline_checkpoints/stage3_uncertainty_summary.csv
#         PNG plots in ./baseline_checkpoints/
# =========================================================

import os
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

BASE_DIR = "./baseline_checkpoints"
os.makedirs(BASE_DIR, exist_ok=True)

stage2_path = os.path.join(BASE_DIR, "temperature_scaling_stage2.pt")
stage3_out  = os.path.join(BASE_DIR, "uncertainty_stage3.pt")

if not os.path.exists(stage2_path):
    raise FileNotFoundError(f"❌ Stage 2 file not found: {stage2_path} (run Stage 2 first)")

s2 = torch.load(stage2_path, map_location="cpu")

required = ["temperature", "val_logits_calibrated", "test_logits_calibrated", "val_labels", "test_labels"]
missing = [k for k in required if k not in s2]
if missing:
    print("Available keys in Stage 2:", list(s2.keys()))
    raise KeyError(f"❌ Missing keys in Stage 2 file: {missing}")

T = float(s2["temperature"])
val_logits_cal  = s2["val_logits_calibrated"].float()
test_logits_cal = s2["test_logits_calibrated"].float()
val_labels  = s2["val_labels"].long()
test_labels = s2["test_labels"].long()

print("✅ Loaded Stage 2:", stage2_path)
print(f"Temperature T = {T:.4f}")
print("VAL logits:", tuple(val_logits_cal.shape), "| VAL labels:", tuple(val_labels.shape))
print("TEST logits:", tuple(test_logits_cal.shape), "| TEST labels:", tuple(test_labels.shape))

# -----------------------------
# Calibrated probabilities
# -----------------------------
val_probs  = torch.softmax(val_logits_cal, dim=1)
test_probs = torch.softmax(test_logits_cal, dim=1)

eps = 1e-12

def confidence(p: torch.Tensor) -> torch.Tensor:
    return p.max(dim=1).values

def entropy(p: torch.Tensor) -> torch.Tensor:
    return -(p * (p + eps).log()).sum(dim=1)

def margin(p: torch.Tensor) -> torch.Tensor:
    top2 = torch.topk(p, k=2, dim=1).values
    return top2[:, 0] - top2[:, 1]

# Metrics (VAL + TEST)
val_conf = confidence(val_probs)
test_conf = confidence(test_probs)

val_ent = entropy(val_probs)
test_ent = entropy(test_probs)

val_mar = margin(val_probs)
test_mar = margin(test_probs)

val_vr = 1.0 - val_conf
test_vr = 1.0 - test_conf

# Predictions (calibrated probs; argmax unchanged vs logits/T)
val_pred  = val_probs.argmax(dim=1)
test_pred = test_probs.argmax(dim=1)

# -----------------------------
# Save Stage 3 for Stage 4
# -----------------------------
torch.save({
    "temperature": T,

    "val_labels": val_labels,
    "test_labels": test_labels,

    "val_pred": val_pred,
    "test_pred": test_pred,

    "val_confidence": val_conf,
    "test_confidence": test_conf,

    "val_entropy": val_ent,
    "test_entropy": test_ent,

    "val_margin": val_mar,
    "test_margin": test_mar,

    "val_variation_ratio": val_vr,
    "test_variation_ratio": test_vr,
}, stage3_out)

print("✅ Saved Stage 3 file:", stage3_out)

# -----------------------------
# CSV summary
# -----------------------------
def summarize(name, x):
    x = x.detach().cpu().numpy()
    return {
        "metric": name,
        "mean": float(np.mean(x)),
        "std": float(np.std(x)),
        "min": float(np.min(x)),
        "max": float(np.max(x)),
    }

rows = [
    summarize("VAL_confidence", val_conf),
    summarize("VAL_entropy", val_ent),
    summarize("VAL_margin", val_mar),
    summarize("VAL_variation_ratio", val_vr),
    summarize("TEST_confidence", test_conf),
    summarize("TEST_entropy", test_ent),
    summarize("TEST_margin", test_mar),
    summarize("TEST_variation_ratio", test_vr),
]

df_sum = pd.DataFrame(rows)
csv_path = os.path.join(BASE_DIR, "stage3_uncertainty_summary.csv")
df_sum.to_csv(csv_path, index=False)
print("✅ Saved CSV summary:", csv_path)

# -----------------------------
# Plots: Correct vs Wrong (TEST)
# -----------------------------
test_correct = (test_pred == test_labels).detach().cpu().numpy()

def hist_correct_wrong(values_torch, title, xlabel, filename, bins=60):
    v = values_torch.detach().cpu().numpy()
    plt.figure(figsize=(9,5))
    plt.hist(v[test_correct], bins=bins, alpha=0.6, label="Correct")
    plt.hist(v[~test_correct], bins=bins, alpha=0.6, label="Wrong")
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Count")
    plt.grid(True, alpha=0.25)
    plt.legend()
    out_path = os.path.join(BASE_DIR, filename)
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.show()
    print("✅ Saved:", out_path)

hist_correct_wrong(test_conf, "Stage 3 (TEST): Confidence (Correct vs Wrong)", "Confidence (max prob)", "stage3_hist_confidence.png")
hist_correct_wrong(test_ent,  "Stage 3 (TEST): Entropy (Correct vs Wrong)",    "Entropy",             "stage3_hist_entropy.png")
hist_correct_wrong(test_mar,  "Stage 3 (TEST): Margin (Correct vs Wrong)",     "Margin (p1 - p2)",    "stage3_hist_margin.png")
hist_correct_wrong(test_vr,   "Stage 3 (TEST): Variation Ratio (Correct vs Wrong)", "Var ratio (1-confidence)", "stage3_hist_variation_ratio.png")

# -----------------------------
# Boxplots by class (TEST)
# -----------------------------
num_classes = int(test_labels.max().item()) + 1
class_names = ["sadness","joy","love","anger","fear","surprise"] if num_classes == 6 else [f"class_{i}" for i in range(num_classes)]
y_true = test_labels.detach().cpu().numpy()

def boxplot_by_class(values_torch, title, ylabel, filename):
    v = values_torch.detach().cpu().numpy()
    data = [v[y_true == c] for c in range(num_classes)]
    plt.figure(figsize=(10,5))
    plt.boxplot(data, tick_labels=class_names, showfliers=False)  # ✅ updated arg name
    plt.title(title)
    plt.ylabel(ylabel)
    plt.xticks(rotation=25, ha="right")
    plt.grid(True, axis="y", alpha=0.25)
    out_path = os.path.join(BASE_DIR, filename)
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.show()
    print("✅ Saved:", out_path)

boxplot_by_class(test_conf, "Stage 3 (TEST): Confidence by class", "Confidence", "stage3_box_confidence_by_class.png")
boxplot_by_class(test_ent,  "Stage 3 (TEST): Entropy by class",    "Entropy",    "stage3_box_entropy_by_class.png")
boxplot_by_class(test_mar,  "Stage 3 (TEST): Margin by class",     "Margin",     "stage3_box_margin_by_class.png")
boxplot_by_class(test_vr,   "Stage 3 (TEST): Variation Ratio by class", "Var ratio", "stage3_box_variation_ratio_by_class.png")

print("\n✅ Stage 3 finished. Outputs saved in baseline_checkpoints/.")

# =========================================================
# STAGE 4 (UPDATED): Selective Prediction + Risk–Coverage Sweep
# Uses calibrated logits from Stage 2 (temperature scaling)
#
# Requires:
#   ./baseline_checkpoints/temperature_scaling_stage2.pt
#     keys: val_logits_calibrated, test_logits_calibrated, val_labels, test_labels, temperature
#
# Outputs:
#   ./baseline_checkpoints/selective_stage4_sweep.csv
#   ./baseline_checkpoints/stage4_risk_coverage_sweep.png
#   ./baseline_checkpoints/stage4_accuracy_coverage_sweep.png
#   ./baseline_checkpoints/selective_stage4.pt   (stores chosen mode + thresholds)
# =========================================================

import os
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score

OUT_DIR = "./baseline_checkpoints"
os.makedirs(OUT_DIR, exist_ok=True)

stage2_path = os.path.join(OUT_DIR, "temperature_scaling_stage2.pt")
stage4_pt   = os.path.join(OUT_DIR, "selective_stage4.pt")
csv_out     = os.path.join(OUT_DIR, "selective_stage4_sweep.csv")

if not os.path.exists(stage2_path):
    raise FileNotFoundError(f"Missing Stage 2 file: {stage2_path}")

s2 = torch.load(stage2_path, map_location="cpu")

required = ["val_logits_calibrated", "test_logits_calibrated", "val_labels", "test_labels"]
missing = [k for k in required if k not in s2]
if missing:
    print("Stage 2 keys:", list(s2.keys()))
    raise KeyError(f"Stage 2 missing keys: {missing}")

val_logits = s2["val_logits_calibrated"].float()
test_logits = s2["test_logits_calibrated"].float()
val_y = s2["val_labels"].long().numpy()
test_y = s2["test_labels"].long().numpy()

val_probs = torch.softmax(val_logits, dim=1)
test_probs = torch.softmax(test_logits, dim=1)

val_pred = val_probs.argmax(dim=1).numpy()
test_pred = test_probs.argmax(dim=1).numpy()

# -----------------------------
# Uncertainty definition
# Higher value = MORE uncertain
# -----------------------------
UNCERTAINTY_MODE = "entropy"   # "entropy", "margin", "var_ratio", "confidence"
eps = 1e-12

def u_entropy(p):
    return -(p * (p + eps).log()).sum(dim=1)

def u_var_ratio(p):
    conf = p.max(dim=1).values
    return 1.0 - conf

def u_confidence(p):
    conf = p.max(dim=1).values
    return 1.0 - conf

def u_margin(p):
    top2 = torch.topk(p, k=2, dim=1).values
    mar = top2[:, 0] - top2[:, 1]  # higher = more confident
    return 1.0 - mar               # convert to uncertainty

def compute_u(p, mode):
    mode = mode.lower()
    if mode == "entropy":
        return u_entropy(p).numpy()
    if mode in ["var_ratio", "variation_ratio"]:
        return u_var_ratio(p).numpy()
    if mode == "confidence":
        return u_confidence(p).numpy()
    if mode == "margin":
        return u_margin(p).numpy()
    raise ValueError(f"Unknown UNCERTAINTY_MODE: {mode}")

val_u = compute_u(val_probs, UNCERTAINTY_MODE)
test_u = compute_u(test_probs, UNCERTAINTY_MODE)

# -----------------------------
# Sweep coverages (as in your methodology)
# -----------------------------
coverages = [1.00, 0.95, 0.90, 0.85, 0.80, 0.70]

rows = []
thresholds = {}

for cov in coverages:
    # accept if u <= threshold; choose threshold on VAL to hit desired coverage
    thr = float(np.quantile(val_u, cov))
    thresholds[cov] = thr

    val_accept = (val_u <= thr)
    test_accept = (test_u <= thr)

    # Metrics on accepted subset
    yv = val_y[val_accept]; pv = val_pred[val_accept]
    yt = test_y[test_accept]; pt = test_pred[test_accept]

    val_acc = accuracy_score(yv, pv) if len(yv) else np.nan
    val_mf1 = f1_score(yv, pv, average="macro") if len(yv) else np.nan
    val_risk = 1.0 - val_acc if len(yv) else np.nan

    test_acc = accuracy_score(yt, pt) if len(yt) else np.nan
    test_mf1 = f1_score(yt, pt, average="macro") if len(yt) else np.nan
    test_risk = 1.0 - test_acc if len(yt) else np.nan

    rows.append({
        "mode": UNCERTAINTY_MODE,
        "target_coverage_val": cov,
        "threshold_from_val": thr,
        "val_coverage_actual": float(val_accept.mean()),
        "val_accuracy_accepted": float(val_acc),
        "val_macro_f1_accepted": float(val_mf1),
        "val_risk_accepted": float(val_risk),
        "test_coverage_actual": float(test_accept.mean()),
        "test_accuracy_accepted": float(test_acc),
        "test_macro_f1_accepted": float(test_mf1),
        "test_risk_accepted": float(test_risk),
        "accepted_test_n": int(test_accept.sum()),
        "rejected_test_n": int((~test_accept).sum()),
    })

df = pd.DataFrame(rows)
df.to_csv(csv_out, index=False)
print("✅ Saved sweep CSV:", csv_out)
print(df[[
    "target_coverage_val","val_coverage_actual","test_coverage_actual",
    "test_accuracy_accepted","test_macro_f1_accepted","test_risk_accepted"
]])

# -----------------------------
# Plots: Risk–Coverage + Accuracy–Coverage (VAL & TEST)
# -----------------------------
plt.figure(figsize=(7,6))
plt.plot(df["val_coverage_actual"], df["val_risk_accepted"], marker="o", label="VAL")
plt.plot(df["test_coverage_actual"], df["test_risk_accepted"], marker="o", label="TEST")
plt.xlabel("Coverage (fraction accepted)")
plt.ylabel("Risk (1 - accuracy on accepted)")
plt.title(f"Stage 4: Risk–Coverage Sweep ({UNCERTAINTY_MODE})")
plt.grid(True, alpha=0.3)
plt.legend()
p1 = os.path.join(OUT_DIR, "stage4_risk_coverage_sweep.png")
plt.savefig(p1, dpi=200, bbox_inches="tight")
plt.show()
print("💾 Saved:", p1)

plt.figure(figsize=(7,6))
plt.plot(df["val_coverage_actual"], df["val_accuracy_accepted"], marker="o", label="VAL")
plt.plot(df["test_coverage_actual"], df["test_accuracy_accepted"], marker="o", label="TEST")
plt.xlabel("Coverage (fraction accepted)")
plt.ylabel("Accuracy on accepted")
plt.title(f"Stage 4: Accuracy–Coverage Sweep ({UNCERTAINTY_MODE})")
plt.grid(True, alpha=0.3)
plt.legend()
p2 = os.path.join(OUT_DIR, "stage4_accuracy_coverage_sweep.png")
plt.savefig(p2, dpi=200, bbox_inches="tight")
plt.show()
print("💾 Saved:", p2)

# -----------------------------
# Save thresholds for reproducibility
# -----------------------------
torch.save({
    "uncertainty_mode": UNCERTAINTY_MODE,
    "coverages": coverages,
    "thresholds_from_val": thresholds,
}, stage4_pt)
print("✅ Saved Stage 4 thresholds file:", stage4_pt)

!zip -r baseline_checkpoints.zip baseline_checkpoints

from google.colab import files
files.download("baseline_checkpoints.zip")